language: java
jdk: openjdk12
sudo: required
before_script:
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install heroku-cli-deploy
script: skip
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Drevision=${TRAVIS_COMMIT} -B -V
test: mvn test -Drevision=${TRAVIS_COMMIT} -B
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
  - mv target/UofU-CS-Bot.jar .
deploy:
  provider: script
  script:
    - heroku deploy:jar portfolio.jar --app mitchtalmadge-uofu-cs-bot
  on:
    branch: master
