language: java
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: Vrv0Io1Oy/Htv7E06jVYin5H9kD8p2B7VKctpaWOrWrlOpnuF7x2AGUcDgBdY3QB/eFOikPCu6HF6OTpFpbku7/iJdgM95SSMBZZAnIUN2+K0FIS1jlLTj5/2h+PIBYeJrQ3zI+icA3B7LebjtTFq9A+yBdLL6eNFGat/nQBxFahjUd68fxkRHPeA3wlHqffB2kuqxR3Xm2eZLgvmquJeGjE/J/MI7MAn65CLce06der/tZNdt4a9W2ywPyvGMPUMKXXde9O+GGRasVh4sjP+cHmzPpIQYKlc4VD7ngp89buTrqViNbE+XEHj3vE3NKYRKkNGRc7P5lpqhWnxGD46SnN2h+368bYtiEeUlg4efcrtS5ZfLhQu19kb1pPCROIF5DXSaAKFEoRr40pahIbPKx3XpMVUVW8e9pwpy16W2+886OfW7GpV8ZhDnwckMN4WTvabaXBkvHJVGkbtFgLJzweDZ4euh1r7pgdhJW2BDLrqblAIfk/UqUnG3TTzU08YeqhGRTTbnfIwfYDv4kHtQ+Udo6oaoYe4XI/2Q9KINQau3gMi1QKZPpiUUjWMtaub2lbOWHfhwXkfYLxi0KilqQMkEg+cKFDRpmgOZawTZO5LhPsfj/27B9chzfnSacZ4M1ZvWryQl7bQwhizfKugU6dCnumotv0vhLvMNX11+s=
  app: mitchtalmadge-uofu-cs-bot
  on:
    tags: true
