language: java
jdk: openjdk12
sudo: required
cache:
  directories:
    - "$HOME/.m2"

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Drevision=${TRAVIS_COMMIT} -B -V
script: mvn test -Drevision=${TRAVIS_COMMIT} -B

before_deploy:
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install heroku-cli-deploy
  - mv target/UofU-CS-Bot.jar .
deploy:
  provider: script
  script:
    - heroku deploy:jar portfolio.jar --app mitchtalmadge-uofu-cs-bot
  on:
    branch: master
